<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260422162231 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE deck (id UUID NOT NULL, name VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, format VARCHAR(50) DEFAULT NULL, is_public BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, stats JSON DEFAULT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_deck_user ON deck (user_id)');
        $this->addSql('CREATE INDEX idx_deck_format ON deck (format)');
        $this->addSql('CREATE TABLE deck_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, card_reference VARCHAR(100) NOT NULL, quantity SMALLINT NOT NULL, deck_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2AF3DCED111948DC ON deck_card (deck_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_deck_card ON deck_card (deck_id, card_reference)');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, keycloak_id VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, username VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649491914B1 ON "user" (keycloak_id)');
        $this->addSql('ALTER TABLE deck ADD CONSTRAINT FK_4FAC3637A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE deck_card ADD CONSTRAINT FK_2AF3DCED111948DC FOREIGN KEY (deck_id) REFERENCES deck (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE deck DROP CONSTRAINT FK_4FAC3637A76ED395');
        $this->addSql('ALTER TABLE deck_card DROP CONSTRAINT FK_2AF3DCED111948DC');
        $this->addSql('DROP TABLE deck');
        $this->addSql('DROP TABLE deck_card');
        $this->addSql('DROP TABLE "user"');
    }
}
