services:
    altered_core.mock_http_client:
        class: Symfony\Component\HttpClient\MockHttpClient
        public: true

    App\Client\AlteredCoreClient:
        autowire: true
        arguments:
            $httpClient: '@altered_core.mock_http_client'
            $alteredCoreUrl: '%env(ALTERED_CORE_URL)%'
